Kernel360/F2-omocha-BE

- .gitignore
- Dockerfile
- build.gradle
- omocha-client/build.gradle
- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
- omocha-client/src/main/resources/application-prod.yml
- omocha-client/src/main/resources/logback-spring-prod.xml
- omocha-client/src/main/resources/logback-spring.xml
- omocha-domain/build.gradle
- 기능 : Production 환경 설정 파일 추가 및 gradle 파일 수정
- issue : #9 
- Close #9
> [FEAT] 운영 환경 설정

- .github/workflows/deploy-CICD.yml
- build.gradle
- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
- omocha-client/src/main/java/org/auction/client/common/code/AuctionCode.java
- omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
- omocha-client/src/main/java/org/auction/client/exception/member/InvalidMemberException.java
- omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
- omocha-client/src/main/resources/application.yml
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/AuctionRepository.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/condition/AuctionSearchCondition.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
- 기능 : 전체 게시글 조회 수정
- issue : #22 
- Close #22
> [FEAT] 전체 게시글 조회 수정

- omocha-client/src/main/java/org/auction/client/config/security/CustomCorsConfig.java
- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- omocha-client/src/main/resources/application.yml
- 기능 : cors 설정 수정
- issue : #29 
- cookie에 domain 설정
- cors 설정에 프론트 도메인 추가
- Close #ISSUE_NUMBER
> [FIX] 프론트 배포 후 cors 오류 수정

- omocha-client/build.gradle
- omocha-client/src/main/java/org/auction/client/common/code/OauthCode.java
- omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
- omocha-client/src/main/java/org/auction/client/config/security/filter/JwtAuthFilter.java
- omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAccessDeniedHandler.java
- omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAuthenticationEntryPointHandler.java
- omocha-client/src/main/java/org/auction/client/config/security/handler/OAuth2FailureHandler.java
- omocha-client/src/main/java/org/auction/client/config/security/handler/OAuth2SuccessHandler.java
- omocha-client/src/main/java/org/auction/client/exception/oauth/OauthException.java
- omocha-client/src/main/java/org/auction/client/exception/oauth/UnsupportedOAuthProviderException.java
- omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- omocha-client/src/main/java/org/auction/client/oauth/OAuth2UserInfo.java
- omocha-client/src/main/java/org/auction/client/oauth/application/CustomOAuth2UserService.java
- omocha-client/src/main/resources/application.yml
- 기능 : OAuth 로그인 구현
- issue : #21 
- Google, Naver OAuth 로그인 구현
- OAuth를 통해 사용자 정보를 제공받아 회원가입 여부 판단 후 회원가입 처리
- favicon.ico 요청 임시 처리
- JWT domain 설정 분기(local, prod)
- Close #21
> [FEAT] OAuth 로그인 구현

- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/request/CreateAuctionRequest.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/BidController.java
- omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
- omocha-client/src/main/java/org/auction/client/jwt/UserPrincipal.java
- omocha-client/src/main/java/org/auction/client/jwt/application/CustomUserDetailsService.java
- omocha-client/src/main/resources/logback-spring-local.xml
- omocha-domain/src/main/java/org/auction/domain/auction/domain/entity/AuctionEntity.java
- omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
- 기능 : 입찰 기능, 사용자 정보 반환
- issue : #34 
입찰 기능 수정, 상세조회 요청 시 현재가격 (nowPrice)도 반환 추가
사용자 로그인 정보를 annotation으로 쉽게 불러오기
- Close #34
> [FIX] 입찰 기능 수정 및 @Authentication 수정

- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/BidRepository.java
- 기능 : bid 총 개수 count
- issue : #36 
상세 조회, 전체 조회 시 BID 전체 count 개수 같이 반환
bid service 에 repository에서 count 개수 반환하는 코드 구현
- Close #ISSUE_NUMBER
> [FEAT] bid 총 개수 count 구현

- build.gradle
- omocha-client/build.gradle
- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionController.java
- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-domain/src/main/java/org/auction/domain/auction/domain/enums/AuctionStatus.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
- 기능 : 경매 전체 게시글 조회에서 PREBID, BIDDING, CONCLUDED, COMPLETED 처럼 상태를 조회할수 있게 추가
- issue : #41 
Swagger 설정 변경. drop down 이 가능하게 변경
Sorting, Direction 설정 하는게 원래 createAt, DESC 였는데 sorting, direction을 파라미터로 따로 분리함
- Close #41
> [FEAT] 경매 상태(Status) 조회 추가

- omocha-client/src/main/java/org/auction/client/config/security/CustomCorsConfig.java
- 기능 : cors 에러 수정
- issue : #45 
- local.omocha-auction.com cors 에러 수정
- Close #45
> [FIX] local.omocha-auction.com cors 에러 수정

- .github/workflows/deploy-CICD.yml
- docker-compose.yaml
- 기능 : Github action CI/CD 배포 수정
- issue : #40 
- github action cloud 환경 ip 주소 받아서 aws 인바운드 규칙에 추가 및 삭제
- docker compose에 spring boot 추가하여 자동 배포되도록 수정
- Close #40
> [FIX] Github action CI/CD 배포 수정

- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- 기능 : Cookie 만료시간 수정
- issue : #48 
- Cookie 만료시간 수정
- jwt와 cookie의 expire값을 분리
- Close #48
> [FIX] Cookie 만료시간 수정

- omocha-client/src/main/java/org/auction/client/common/code/MypageCode.java
- omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
- omocha-client/src/main/java/org/auction/client/exception/mypage/MypageException.java
- omocha-client/src/main/java/org/auction/client/mypage/application/MypageService.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageApi.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageController.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MemberInfoResponse.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MypageAuctionListResponse.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/response/MypageBidListResponse.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryCustom.java
- omocha-domain/src/main/java/org/auction/domain/auction/infrastructure/custom/AuctionRepositoryImpl.java
- omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/BidRepository.java
- omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/custom/BidRepositoryCustom.java
- omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/custom/BidRepositoryImpl.java
- 기능 : mypage 기능 추가
- issue : #39
* feat : 사용자 정보 반환 코드 추가
* feat : 사용자 경매 물품 내역 조회
* feat : 사용자 입찰 내역 조회 추가
* feat : mypage 관련 error, Api 추가
> [FEAT] mypage 기능 추가

- omocha-client/src/main/java/org/auction/client/common/code/MemberCode.java
- omocha-client/src/main/java/org/auction/client/member/interfaces/AuthApi.java
- omocha-client/src/main/java/org/auction/client/member/interfaces/AuthController.java
- 기능 : Logout API 구현
- issue : #65 
- Logout API 구현
- Close #65
> [FEAT] Logout API 구현

- omocha-client/src/main/resources/application.yml
- omocha-client/src/main/resources/logback-spring-local.xml
- omocha-client/src/main/resources/logback-spring-prod.xml
- 기능 : 배포환경 Redirect Uri 수정
- issue : #67 
- 배포환경 Redirect Uri 수정
- Close #67
> [FIX] 배포환경 Redirect Uri 수정

- .github/workflows/deploy-CICD.yml
- 기능 : CD시 docker hub login 문제 해결
- issue : #70 
- CD시 docker hub login 안되던 문제 해결
- Close #70
> [FIX] CD시 docker hub login 문제 해결

- .github/workflows/deploy-CICD.yml
- docker-compose.yaml
- omocha-client/src/main/resources/application.yml
- 기능 : CD 시 docker sudo 부여
- issue : #70 
- CD 시 docker sudo 부여
- Close #70
> [FEAT] CD 시 docker sudo 부여

- omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
- omocha-client/src/main/java/org/auction/client/oauth/OAuth2UserInfo.java
- omocha-domain/src/main/java/org/auction/domain/member/domain/entity/MemberEntity.java
- 기능 : OAuth username 받도록 처리
- issue : #78 #75 
- OAuth에서 username을 찾지 못해 로그인 처리가 되지 않던 문제 해결
- OAuth에서 사용자 이름을 받아와서 저장하도록 처리
- BidPrice 에러 누락본 추가
- Close #78
> [FIX] OAuth username 받도록 처리

- omocha-client/src/main/java/org/auction/client/auction/interfaces/AuctionApi.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
- omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomApi.java
- omocha-client/src/main/java/org/auction/client/config/swagger/SwaggerConfig.java
- omocha-client/src/main/java/org/auction/client/member/interfaces/AuthApi.java
- omocha-client/src/main/java/org/auction/client/mypage/interfaces/MypageApi.java
- omocha-client/src/main/java/org/auction/client/qna/interfaces/AnswerApi.java
- omocha-client/src/main/java/org/auction/client/qna/interfaces/QuestionApi.java
- omocha-client/src/main/resources/application.yml
- omocha-client/src/main/resources/logback-spring-local.xml
- omocha-client/src/main/resources/logback-spring-prod.xml
- **기능**: Swagger에 `@Tag` 애너테이션 추가
- **issue**: #80
- 각 컨트롤러에 Swagger `@Tag` 애너테이션을 추가하여 API를 그룹화하고 설명을 제공
```java
@Tag(name = "채팅방 API", description = "채팅방 생성 및 조회를 위한 API입니다.")
public interface ChatRoomApi {
// 구현 내용 생략
}
```
- **@Tag 애너테이션으로 채팅방 API를 그룹화.**  
- **description 필드를 통해 API 설명을 Swagger UI에 추가.**
- **@Tag가 있는 컨트롤러는 Swagger UI에 그룹으로 표시되며, 각 API 설명이 명확히 보인다.**
- Close #80
> [FEAT] swagger tag 추가

- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/common/code/AuctionCode.java
- omocha-client/src/main/java/org/auction/client/exception/auction/AuctionHasBidsException.java
- 기능 : 입찰 걸린 경매 삭제 불가 처리
- issue : #85 
- 입찰 걸린 경매 삭제 불가 처리
- Close #85
> [FIX] 입찰 걸린 경매 삭제 불가 처리

- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
- omocha-client/src/main/java/org/auction/client/config/security/handler/CustomAuthenticationEntryPointHandler.java
- omocha-client/src/main/java/org/auction/client/exception/bid/InvalidBidUnitException.java
- omocha-client/src/main/java/org/auction/client/exception/bid/SelfBidNotAllowedException.java
- 기능 : 입찰 로직에 Exception 추가
- issue : #94 
- 자신의 경매에 입찰을 걸 경우 Exception 발생
- BitUnit에 맞지 않는 입찰을 걸 경우 Exception 발생
- 401 에러 디버깅을 위해 코드 임시 추가
- 현재 배포 서버에서 발생하는 알 수 없는 401 에러를 디버깅 하기 위해 임시로 코드를 추가하였습니다. 해당 코드는 추후 삭제하도록 하겠습니다.
- Close #94
> [FIX] 입찰 로직에 Exception 추가

- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionDetailResponse.java
- omocha-client/src/main/java/org/auction/client/auction/interfaces/response/AuctionListResponse.java
- omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
- omocha-domain/src/main/java/org/auction/domain/bid/infrastructure/ConcludeRepository.java
- 기능 : Auction 관련 reponse에 속성 추가
- issue : #96 
- AuctionDetailResponse
- sellerId, status, concludePrice 추가
- AuctionListResponse
- status, concludePrice 추가
- Close #96
> [FIX] Auction 관련 reponse에 속성 추가

- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- 기능 : 입찰 BidUnit 체크 오류 수정
- issue : #99 
- 입찰 BidUnit 체크 시 시작가를 고려하여 처리하도록 수정
- Close #99
> [FIX] 입찰 BidUnit 체크 오류 수정

- omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- omocha-client/src/main/java/org/auction/client/jwt/util/JwtUtil.java
- 기능 : 배포환경 로그아웃 시 쿠키 사라지지 않는 문제 해결
- issue : #109 
- 로그아웃 시 cookie secure(true) 설정
- 토큰 만료시간 롤백
- security config 개행 수정
- Close #109
> [FIX] 배포환경 로그아웃 시 쿠키 사라지지 않는 문제 해결

- omocha-client/src/main/java/org/auction/client/auction/application/AuctionService.java
- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-client/src/main/java/org/auction/client/bid/application/ConcludeService.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/BidApi.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/BidController.java
- omocha-client/src/main/java/org/auction/client/bid/interfaces/response/NowPriceResponse.java
- omocha-client/src/main/java/org/auction/client/chat/interfaces/ChatRoomController.java
- omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
- omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
- omocha-client/src/main/java/org/auction/client/mypage/application/MypageService.java
- 기능 : 현재가 조회 API 추가
- issue : #108 
- 현재가 조회 API 추가
- getCurrentHighestBid가 AuctionEntity가 아닌 AuctionId를 받도록 변경
- Close #108
> [FEAT] 현재가 조회 API 추가

- omocha-client/src/main/java/org/auction/client/bid/application/BidService.java
- omocha-client/src/main/java/org/auction/client/common/code/BidCode.java
- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- 기능 : 현재가와 동일한 입찰가 막기
- issue : #115 
- 현재가와 동일한 입찰가 막기
- 토큰 유효시간도 수정
- Close #115
> [FIX] 현재가와 동일한 입찰가 막기

- omocha-client/src/main/java/org/auction/client/config/security/SecurityConfig.java
- omocha-client/src/main/java/org/auction/client/jwt/application/JwtService.java
- omocha-client/src/main/java/org/auction/client/jwt/util/JwtUtil.java
- 기능 : resetCookie가 배포환경에서 적용되지 않는 문제
- issue : #109 
- resetCookie를 setCookie와 동일한 형식으로 변경
- Close #109
> [FIX] resetCookie를 setCookie와 동일한 형식으로 변경
